name: Schedule Send Mails

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  send-mails:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: lilmailing-send-mails
      cancel-in-progress: false
    
    container:
      image: ghcr.io/${{ github.repository_owner }}/Dumpmail:latest
    
    env:
      USER_ID: ${{ secrets.USER_ID }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}
    

    steps:
      - run: pnpm job:send